ConfigVersion : 1
capacity:
    mining:
      tier1: 64
      tier2: 128
      tier3: 256
    wood:
      tier1: 64
      tier2: 128
      tier3: 256
    farming:
      tier1: 64
      tier2: 128
      tier3: 256